name: Testing

on:
  push:
    branches:
    - issue-*
    - milestone-*
    - project-*

jobs:
  Perl-0000:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v1
    - name: Setup Git User
      run: git config --global user.name "Al Newkirk"
    - name: Setup Git Email
      run: git config --global user.email "awncorp@cpan.org"
    - name: Setup GitHub User
      run: git config --global github.user ${{ secrets.GithubUser }}
    - name: Setup GitHub Token
      run: git config --global github.user ${{ secrets.GithubToken }}
    - name: Install CPANM
      run: sudo apt install -y cpanminus
    - name: Install Perl::Critic
      run: sudo cpanm -qn Perl::Critic
    - name: Install Project Dependencies
      run: sudo cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: perlcritic lib t
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9
        TESTDB_INITIAL: postgres
        TESTDB_DATABASE: zing
        TESTDB_HOSTNAME: localhost
        TESTDB_HOSTPORT: 5432
        TESTDB_USERNAME: postgres
        TESTDB_PASSWORD: postgres